"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var cancion_1 = require("./cancion");
var titulo1 = "La Bamba";
var autor1 = "Los Lobos";
var titulo2 = "Se fue";
var autor2 = "Laura Pausinni";
var titulo3 = "Quisiera ser la otra";
var autor3 = "Ana Gabriel";
var cancion1 = new cancion_1.Cancion(titulo1, autor1);
var cancion2 = new cancion_1.Cancion(titulo2, autor2);
var cancion3 = new cancion_1.Cancion(titulo3, autor3);
console.log("Cancion 1: " + cancion1.dameTitulo() + " de " + cancion1.dameAutor());
console.log("Cancion 2: " + cancion2.dameTitulo() + " de " + cancion2.dameAutor());
console.log("Cancion 3: " + cancion3.dameTitulo() + " de " + cancion3.dameAutor());
cancion1.ponTitulo("Me dedique a perderte");
cancion1.ponAutor("Alejandro Fernandez");
console.log("Cancion 1: " + cancion1.dameTitulo() + " de " + cancion1.dameAutor());
